<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../../external_programs/AudioService/GetMusicStatus/MusicServices/SPlayerNextService.cs" Link="SPlayerNextService.cs" />
    <Compile Include="../../external_programs/AudioService/GetMusicStatus/MusicServices/MusicService.cs" Link="MusicService.cs" />
    <Reference Include="CSCore"><HintPath>../../Assets/AudioService/CSCore.dll</HintPath></Reference>
    <Reference Include="Newtonsoft.Json"><HintPath>../../Assets/AudioService/Newtonsoft.Json.dll</HintPath></Reference>
  </ItemGroup>
</Project>
